# Generated by Django 5.2.5 on 2025-08-15 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('internal_status', models.CharField(blank=True, max_length=255)),
                ('external_status', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=350, null=True)),
                ('parent_code', models.CharField(blank=True, max_length=10)),
                ('status_code', models.CharField(max_length=10, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'unique_together': {('internal_status', 'parent_code')},
            },
        ),
    ]
