# Generated by Django 5.2.5 on 2025-08-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='educationinfo',
            options={'verbose_name': 'Education Info'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Personal Info'},
        ),
        migrations.AlterModelOptions(
            name='workinfo',
            options={'verbose_name': 'Work Info'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='residential_status',
            field=models.CharField(blank=True, choices=[('singaporean', 'Singaporean'), ('permanent_resident', 'Permanent Resident'), ('employment_pass', 'Employment Pass Holder'), ('s_pass', 'S-Pass Holder'), ('work_permit', 'Work Permit Holder'), ('dependent_pass', 'Dependent Pass Holder'), ('long_term_visit_pass', 'Long Term Visit Pass Holder'), ('others', 'Others')], max_length=255, null=True),
        ),
    ]
