# Generated by Django 5.2.5 on 2025-08-17 02:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('memberships', '0002_alter_contactinfo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershippayment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='payment_ref_code',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='payment_year',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='trans_photo',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='trans_ref_no',
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='currency',
            field=models.CharField(default='SGD', max_length=10),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='method',
            field=models.CharField(choices=[('hitpay', 'HitPay'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='period_year',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='provider',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='reference_no',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status'),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, max_length=16, null=True)),
                ('new_status', models.CharField(max_length=16)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='memberships.membershippayment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
