# Generated by Django 5.2.5 on 2025-08-30 04:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('memberships', '0003_remove_membershippayment_payment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='primary_contact',
            new_name='_primary_contact',
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='secondary_contact',
            new_name='_secondary_contact',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='nric_fin',
        ),
        migrations.RemoveField(
            model_name='workflowlog',
            name='workflow_status',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='_nric_fin',
            field=models.CharField(default=1, max_length=255, validators=[django.core.validators.RegexValidator(message='NRIC/FIN must start with S, T, F, or G followed by 7 digits and an alphabet.', regex='^[STFG]\\d{7}[A-Z]$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='new_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_workflow_logs', to='core.status'),
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='old_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_workflow_logs', to='core.status'),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='receipt_no',
            field=models.CharField(editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=16),
        ),
    ]
