# Generated by Django 5.2.5 on 2025-09-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_rename_primary_contact_contactinfo__primary_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='_nric_fin',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='_primary_contact',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='_secondary_contact',
        ),
        migrations.RemoveField(
            model_name='workinfo',
            name='company_contact',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='nric_fin_encrypted',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='primary_contact_encrypted',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='secondary_contact_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_contact_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_education_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_payment_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_work_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workinfo',
            name='company_contact_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
